### ISSUE TITLE
rag_spot_check example bug 2 (LaminiIndex)

### ISSUE THREAD

**Issue by soy-caminante** [lamini-ai/lamini-examples#114]
lamini_index.py: 359 -> EmbeddingGenerator super() init  funtion call has a bug.

`
class EmbeddingGenerator(EmbeddingNode):
    """ 
    Node to generate embeddings, this is intended to be used within 
    the above EmbeddingPipeline.
        
    Parameters
    ----------
    None
        
    """
    
    def __init__(self):
        super().__init__(model_name="meta-llama/Llama-2-7b-chat-hf", max_tokens=5)
`

EmbeddingNode expects a dict as config parameter

`
class EmbeddingGenerator(EmbeddingNode):
    """ 
    Node to generate embeddings, this is intended to be used within 
    the above EmbeddingPipeline.
        
    Parameters
    ----------
    None
        
    """
    
    def __init__(self):
        super().__init__(model_name="meta-llama/Llama-2-7b-chat-hf", config={ "max_tokens" : 5 })
`

**Comment by powerjohnnyli** [comment]
Thanks for reporting @soy-caminante! We pushed an updated `lamini` package version 3.0.4 to address this issue https://github.com/lamini-ai/lamini

in it, we removed the `config` argument and others from EmbeddingNode 
https://github.com/lamini-ai/lamini/blob/main/lamini/generation/embedding_node.py
