### ISSUE TITLE
rag_spot_check example bug 3 (EmbeddingNode)

### ISSUE THREAD

**Issue by soy-caminante** [lamini-ai/lamini-examples#115]
There is another bug: embedding_node.py:73. The EmbeddingNode class does not expect the parameters api_key, api_url or config

`
    def __init__(
        self,
        model_name: Optional[str] = None,
        api_key: Optional[str] = None,
        api_url: Optional[str] = None,
        config: dict = {},
    ):
        super(EmbeddingNode, self).__init__(
            model_name=model_name, api_key=api_key, api_url=api_url, config=config
        )

`
Instead I guess it should be more or less like this (at least, it works for me)

`
    def __init__(
        self,
        model_name: Optional[str] = None,
        api_key: Optional[str] = None,
        api_url: Optional[str] = None,
        config: dict = {},
    ):
        super(AltEmbeddingNode, self).__init__(
            model_name=model_name, max_tokens=config.get("max_tokens", None), max_new_tokens=config.get("max_new_tokens", None)
        )

`

**Comment by soy-caminante** [comment]
This bug affects too to class LaminiEmbeddingModelStage

**Comment by powerjohnnyli** [comment]
Thanks for reporting @soy-caminante! We pushed an updated `lamini` package version 3.0.4 to address this issue https://github.com/lamini-ai/lamini
