### ISSUE TITLE
Status of Prompt Engineering Tutorial

### ISSUE THREAD

**Issue by lbux** [lamini-ai/lamini-examples#26]
Hello, I've been trying to find more resources regarding prompting and few-shot learning. I found the [prompt engineering section](https://github.com/lamini-ai/lamini-sdk/blob/main/02_prompt_engineering/prompt_engineering.md) of this SDK, but I noticed it has a couple TODO sections. I was wondering if its current state is in a complete status (for the time being) or if there are plans to fill in more information?

**Comment by yx-lamini** [comment]
What specific topics in the prompt engineering area?

Note that prompt engineering has become a broad range of techniques: https://www.promptingguide.ai/

**Comment by lbux** [comment]
Thanks for the link. I'll close this issue as the original question is no longer relevant.
