### ISSUE TITLE
lamini.Lamini not working as expected

### ISSUE THREAD

**Issue by vbucaj** [lamini-ai/lamini-examples#27]
I get the following error when running the following block of code:

```from lamini import Lamini

llm = Lamini(model_name="meta-llama/Llama-2-7b-chat-hf")

prompt = "What are llamas?"
my_output = llm.generate(prompt, output_type={"output": "string"})

prompt = ["What are llamas?", "What are alpacs?"]
my_output = llm.generate(prompt, output_type={"output": "string"})
```
I get the same error when providing the path to the locally hosted weights, as well. 

**ERROR:**

```
TypeError                                 Traceback (most recent call last)
Cell In[90], line 6
      3 llm = Lamini(model_name="meta-llama/Llama-2-7b-chat-hf")
      5 prompt = "What are llamas?"
----> 6 my_output = llm.generate(prompt, output_type={"output": "string"})
      8 prompt = ["What are llamas?", "What are alpacs?"]
      9 my_output = llm.generate(prompt, output_type={"output": "string"})

File /usr/local/lib/python3.10/site-packages/lamini/api/lamini.py:68, in Lamini.generate(self, prompt, model_name, output_type, max_tokens, max_new_tokens, callback)
     59 def generate(
     60     self,
     61     prompt: Union[str, List[str]],
   (...)
     66     callback: Optional[Callable] = None,
     67 ):
---> 68     return sync(
     69         self.async_generate(
     70             prompt=prompt,
     71             model_name=model_name,
     72             output_type=output_type,
     73             max_tokens=max_tokens,
     74             max_new_tokens=max_new_tokens,
     75             callback=callback,
     76         )
     77     )

File /usr/local/lib/python3.10/site-packages/lamini/api/synchronize.py:47, in sync(awaitable)
     45 # Get the return or error, return the return or raise the error.
     46 if thread.error is not None:
---> 47     raise thread.error
     48 else:
     49     return thread.ret

File /usr/local/lib/python3.10/site-packages/lamini/api/synchronize.py:35, in sync.<locals>.run_in_new_loop()
     33 try:
     34     loop = asyncio.new_event_loop()
---> 35     th.ret = loop.run_until_complete(awaitable)
     36 except Exception as e:
     37     th.error = e

File /usr/local/lib/python3.10/asyncio/base_events.py:649, in BaseEventLoop.run_until_complete(self, future)
    646 if not future.done():
    647     raise RuntimeError('Event loop stopped before Future completed.')
--> 649 return future.result()

File /usr/local/lib/python3.10/site-packages/lamini/api/lamini.py:110, in Lamini.async_generate(self, prompt, model_name, output_type, max_tokens, max_new_tokens, callback)
    108     if self.max_retries > 0:
    109         print(f"Max retries {self.max_retries} reached")
--> 110     raise e
    111 print(f"Retrying #{retries} in {delay} seconds...")
    112 time.sleep(delay)

File /usr/local/lib/python3.10/site-packages/lamini/api/lamini.py:99, in Lamini.async_generate(self, prompt, model_name, output_type, max_tokens, max_new_tokens, callback)
     97 while retries <= self.max_retries:
     98     try:
---> 99         result = await self.async_inference_queue.submit(
    100             req_data, self.local_cache_file, callback
    101         )
    102         break
    103     except Exception as e:

File /usr/local/lib/python3.10/site-packages/lamini/api/utils/async_inference_queue_3_10.py:55, in AsyncInferenceQueue.submit(self, request, local_cache_file, callback)
     51 if len(exceptions) > 0:
     52     print(
     53         f"Encountered {len(exceptions)} errors during run. Raising first as an exception."
     54     )
---> 55     raise exceptions[0]
     56 # Combine the results and return them
     57 return self.combine_results(results)

File /usr/local/lib/python3.10/site-packages/lamini/api/utils/async_inference_queue_3_10.py:147, in _return_args_and_exceptions(func, *args)
    145 async def _return_args_and_exceptions(func, *args):
    146     try:
--> 147         return *args, await func(*args)
    148     except Exception as e:
    149         return *args, e

File /usr/local/lib/python3.10/site-packages/lamini/api/utils/process_batch.py:52, in process_batch(args)
     46     batch = {
     47         "reservation_id": reservation_api.current_reservation["reservation_id"],
     48         **batch,
     49     }
     51 logger.debug(f"Sending batch")
---> 52 result = await make_async_web_request(client, key, url, "post", batch)
     53 logger.debug(f"Received batch response")
     55 if (
     56     reservation_api.capacity_needed > 0
     57     and reservation_api.capacity_remaining <= 0
     58     and not reservation_api.is_polling
     59 ):

File /usr/local/lib/python3.10/site-packages/lamini/api/rest_requests.py:24, in retry_once.<locals>.wrapped(*args, **kwargs)
     22         result = await func(*args, **kwargs)
     23     else:
---> 24         raise e
     25 return result

File /usr/local/lib/python3.10/site-packages/lamini/api/rest_requests.py:19, in retry_once.<locals>.wrapped(*args, **kwargs)
     17 async def wrapped(*args, **kwargs):
     18     try:
---> 19         result = await func(*args, **kwargs)
     20     except Exception as e:
     21         if lamini.retry:

File /usr/local/lib/python3.10/site-packages/lamini/api/rest_requests.py:34, in make_async_web_request(client, key, url, http_method, json)
     30 @retry_once
     31 async def make_async_web_request(client, key, url, http_method, json=None):
     32     headers = {
     33         "Content-Type": "application/json",
---> 34         "Authorization": "Bearer " + key,
     35     }
     36     assert http_method == "post" or http_method == "get"
     38     try:

TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by apurvakorni** [comment]
Hey! were you able to fix it?

**Comment by vbucaj** [comment]
Still same issue

**Comment by ClaudeCoulombe** [comment]
What works for me:

1. Create an account at app.lamini.ai
2. From your account get a <LAMINI_API_KEY> 
3. Paste your <LAMINI_API_KEY>  in Colab like the code below:

import os
import lamini

lamini.api_key = <LAMINI_API_KEY>

from llama import BasicModelRunner

llm = BasicModelRunner("meta-llama/Llama-2-7b-chat-hf")

prompt = "What are llamas?"
my_output = llm(prompt, output_type={"output": "string"})
print("1-",my_output,"\n")

prompt = ["What are llamas?", "What are alpacs?"]
my_output = llm(prompt, output_type={"output": "string"})
print("2-",my_output,"\n")

prompt = ["What are llamas?", "What are alpacs?"]
my_output = llm(prompt, output_type={"output": "string"})
print("3-",my_output,"\n")

---

LAMINI CONFIGURATION
{}
LAMINI CONFIGURATION
{}
LAMINI CONFIGURATION
{}
1- {'output': 'Llamas are large, domesticated mammals that are native to South America. They are members of the camel family and are known for their distinctive long necks, legs, and ears. Llamas are used for their wool, meat, and as pack animals, and are also kept as pets. They are intelligent, social animals that are known to form close bonds with their owners and other llamas'} 

2- [{'output': 'Llamas are large, domesticated mammals that are native to South America. They are members of the camel family and are known for their distinctive long necks, legs, and ears. Llamas are used for their wool, meat, and as pack animals, and are also kept as pets. They are intelligent, social animals that are known to form close bonds with their owners and other llamas'}, {'output': 'Alpacas are domesticated animals native to South America, known for their soft, luxurious fleece and unique characteristics.\n\nAlpacas are members of the camelid family, which also includes camels and llamas. They are known for their gentle nature and are often used as pack animals, as well as for their fiber. Alpacas are typically smaller than llamas and have a distinctive long-haired coat that is prized for its softness and warmth.\n\nAlpacas are raised for their fiber, which is made into yarn, clothing, and other textiles. The fleece of an alpaca is highly prized for its softness, warmth, and durability, and is often used to make high-quality clothing and textiles. Alpacas are also used for their milk, which is rich in nutrients and is often used to make cheese and other dairy products.\n\nAlpacas are found in a variety of colors, including white, black, brown, and gray, and are often used in breeding programs to create new and unique colors. They are also known for their intelligence and social behavior, and are often kept as pets or used in therapy programs.\n\nOverall, alpacas are fascinating and unique animals that are prized for their fiber, milk, and gentle nature'}] 

3- [{'output': 'Llamas are large, domesticated mammals that are native to South America. They are members of the camel family and are known for their distinctive long necks, legs, and ears. Llamas are used for their wool, meat, and as pack animals, and are also kept as pets. They are intelligent, social animals that are known to form close bonds with their owners and other llamas'}, {'output': 'Alpacas are domesticated animals native to South America, known for their soft, luxurious fleece and unique characteristics.\n\nAlpacas are members of the camelid family, which also includes camels and llamas. They are known for their gentle nature and are often used as pack animals, as well as for their fiber. Alpacas are typically smaller than llamas and have a distinctive long-haired coat that is prized for its softness and warmth.\n\nAlpacas are raised for their fiber, which is made into yarn, clothing, and other textiles. The fleece of an alpaca is highly prized for its softness, warmth, and durability, and is often used to make high-quality clothing and textiles. Alpacas are also used for their milk, which is rich in nutrients and is often used to make cheese and other dairy products.\n\nAlpacas are found in a variety of colors, including white, black, brown, and gray, and are often used in breeding programs to create new and unique colors. They are also known for their intelligence and social behavior, and are often kept as pets or used in therapy programs.\n\nOverall, alpacas are fascinating and unique animals that are prized for their fiber, milk, and gentle nature'}]

**Comment by yx-lamini** [comment]
https://github.com/lamini-ai/lamini-examples/tree/main/01_llama3
Take a look at this example, shows how to start using Lamini SDK.

**Comment by powerjohnnyli** [comment]
@vbucaj It seems like the issue is that you're not authenticated: 
https://lamini-ai.github.io/authenticate/
